doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            App\Language:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Language/Entity'
                prefix: 'App\Language\Entity'
                alias: AppLanguage
            App\User:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/User/Entity'
                prefix: 'App\User\Entity'
                alias: AppUser
            App\Story:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Story/Entity'
                prefix: 'App\Story\Entity'
                alias: AppStory
