doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'App\Migration': '%kernel.project_dir%/migrations'
    storage:
        table_storage:
            table_name: migr_migration
