framework:
    messenger:
        default_bus: default.bus
        buses:
            default.bus: ~
            command.bus: ~
            event.bus:
                default_middleware: allow_no_handlers
            query.bus: ~
            
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            sync: 'sync://'
            async:
                dsn: 'doctrine://default'
                options:
                    table_name: msgr_message
                    queue_name: async
            failed:
                dsn: 'doctrine://default'
                options:
                    table_name: msgr_message
                    queue_name: failed

        routing:
            # Route your messages to the transports
            'App\Common\Domain\Command\CommandInterface': sync
            'App\Common\Domain\Event\EventInterface': async
            'App\Common\Query\Query\QueryInterface': sync
