framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            sync: 'sync://'
            async:
                dsn: 'doctrine://default'
                options:
                    table_name: msgr_message
                    queue_name: async
            failed:
                dsn: 'doctrine://default'
                options:
                    table_name: msgr_message
                    queue_name: failed

        routing:
            # Route your messages to the transports
            'App\Message\SyncMessageInterface': sync
            'App\Message\AsyncMessageInterface': async
