kernel:
    resource: ../../src/Kernel.php
    type: annotation

user_action:
    resource: ../../src/User/Action/
    type: annotation

mercure_action:
    resource: ../../src/Mercure/Action/
    type: annotation