version: '3.8'

services:
  nginx:
    build:
      context: ./docker/nginx
    depends_on:
      - api-gateway-symfony
      - front-web-vue
    volumes:
      - ./apps/api-gateway/app:/www/api-gateway:delegated
      - ./apps/front-web/app:/www/front-web:delegated
      - ./apps/file-manager:/www/file-manager:delegated
      - ./docker/nginx/log:/var/log/nginx:delegated
    ports:
      - 443:443
      - 3001:3001

  api-gateway-symfony:
    build:
      context: ./apps/api-gateway/docker/symfony
    depends_on:
      - api-gateway-postgres
    volumes:
      - ./apps/api-gateway/app:/www/api-gateway:delegated
      - ./apps/api-gateway/jwt:/jwt:delegated
      - ./apps/api-gateway/docker/symfony/log:/var/log:delegated
      - ./apps/api-gateway/docker/sqlite/data:/sqlite/data:delegated
      - ./apps/file-manager:/www/file-manager:delegated

  api-gateway-postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: api_gateway_user
      POSTGRES_PASSWORD: api_gateway_password
      POSTGRES_DB: api_gateway_db
    volumes:
      - ./apps/api-gateway/docker/postgres/data:/var/lib/postgresql/data:delegated
    ports:
      - 5432:5432

  front-web-vue:
    build:
      context: ./apps/front-web/docker/vue
    depends_on:
      - api-gateway-symfony
    volumes:
      - ./apps/front-web/app:/www/front-web:delegated
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
