version: '3.8'

services:

  php:
    build:
      context: ./docker/php
    environment:
      - APP_ENV=dev
      - APP_DEBUG=true
      - APP_SECRET=31522eb5950e8832b5c219fe456205bb
    volumes:
      - .:/var/www:delegated
      - ./docker/php/log:/var/log:delegated

  nginx:
    build:
      context: ./docker/nginx
    depends_on:
      - php
    volumes:
      - .:/var/www:delegated
      - ./docker/nginx/log:/var/log/nginx:delegated
    ports:
      - 443:443