doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/Entity'
                prefix: 'App\Model\Entity'
                alias: App
            App\Language:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Language/Model/Entity'
                prefix: 'App\Language\Model\Entity'
                alias: AppLanguage
            App\User:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/User/Model/Entity'
                prefix: 'App\User\Model\Entity'
                alias: AppUser
            App\Story:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Story/Model/Entity'
                prefix: 'App\Story\Model\Entity'
                alias: AppStory
